---
changelog:
  exclude:
    labels:
      - ignore-for-release
      - tagpr

  categories:
    - title: Features 🎉
      labels: ["enhancement"]
    - title: Bug Fixes 🐌
      labels: ["bug"]
    - title: Documentation 🗒️
      labels: ["documentation"]
    - title: "Dependency Updates 📦"
      labels: ["renovate"]
      exclude:
        labels: ["mise", "github-actions", "docker", "regex", "renovate-config"]
    - title: "Development Environment 🔧"
      labels: ["mise", "github-actions", "docker", "regex", "renovate-config"]
    - title: Other Changes
      labels: ["*"]
