[[mappings]]
tid = 98
name = "HAPPY☆LESSON"
tmdb_series_id = 12427
tmdb_season_id = 2

[[mappings]]
tid = 257
name = "幻影闘士バストフレモン"
tmdb_series_id = 31661
tmdb_season_id = 1

[[mappings]]
tid = 328
name = "天罰エンジェルラビィ☆"
tmdb_series_id = 634622
tmdb_season_id = 0

[[mappings]]
tid = 531
name = "アークエとガッチンポー"
tmdb_series_id = 90460
tmdb_season_id = 1

[[mappings]]
tid = 546
name = "Xenosaga THE ANIMATION"
tmdb_series_id = 34066
tmdb_season_id = 1

[[mappings]]
tid = 581
name = "アークエとガッチンポー てんこもり"
tmdb_series_id = 90460
tmdb_season_id = 2

[[mappings]]
tid = 754
name = "忍風戦隊ハリケンジャー シュシュッとTHE MOVIE"
tmdb_series_id = 200395
tmdb_season_id = 0

[[mappings]]
tid = 815
name = "NIN × NIN 忍者ハットリくん THE MOVIE"
tmdb_series_id = 54150
tmdb_season_id = 0

[[mappings]]
tid = 896
name = "機動警察パトレイバー(TVシリーズ)"
tmdb_series_id = 21736
tmdb_season_id = 1

[[mappings]]
tid = 955
name = "NANA(実写版)"
tmdb_series_id = 29657
tmdb_season_id = 0

[[mappings]]
tid = 975
name = "らぶドル ～Lovely Idol～"
tmdb_series_id = 132994
tmdb_season_id = 1

[[mappings]]
tid = 989
name = "パッタ ポッタ モン太"
tmdb_series_id = 1634997
tmdb_season_id = 0

[[mappings]]
tid = 1114
name = "ラブ★コン"
tmdb_series_id = 27167
tmdb_season_id = 1

[[mappings]]
tid = 1193
name = "ミヨリの森"
tmdb_series_id = 24154
tmdb_season_id = 0

[[mappings]]
tid = 1263
name = "NANA2(実写版)"
tmdb_series_id = 35752
tmdb_season_id = 0

[[mappings]]
tid = 1327
name = "スキージャンプ・ペア～Road to TORINO 2006～"
tmdb_series_id = 101590
tmdb_season_id = 0

[[mappings]]
tid = 1628
name = "スター・ウォーズ／クローン・ウォーズ"
tmdb_series_id = 4194
tmdb_season_id = 0

[[mappings]]
tid = 1690
name = "川の光"
tmdb_series_id = 60707
tmdb_season_id = 0

[[mappings]]
tid = 1741
name = "ミラクル☆トレイン～大江戸線へようこそ～"
tmdb_series_id = 45276
tmdb_season_id = 0

[[mappings]]
tid = 1765
name = "ご姉弟物語"
tmdb_series_id = 275241
tmdb_season_id = 0

[[mappings]]
tid = 1902
name = "スター・ウォーズ／クローン・ウォーズ シーズン2"
tmdb_series_id = 4194
tmdb_season_id = 2

[[mappings]]
tid = 1907
name = "マリー＆ガリー ver.2.0"
tmdb_series_id = 25395
tmdb_season_id = 2

[[mappings]]
tid = 1914
name = "ザ・ペンギンズ from マダガスカル"
tmdb_series_id = 7869
tmdb_season_id = 0

[[mappings]]
tid = 1916
name = "最強武将伝 三国演義"
tmdb_series_id = 81191
tmdb_season_id = 1

[[mappings]]
tid = 2095
name = "Starry☆Sky"
tmdb_series_id = 38303
tmdb_season_id = 1

[[mappings]]
tid = 2175
name = "ザ・ペンギンズ from マダガスカル シーズン2"
tmdb_series_id = 7869
tmdb_season_id = 2

[[mappings]]
tid = 2205
name = "バカとテストと召喚獣にっ！"
tmdb_series_id = 56343
tmdb_season_id = 2

[[mappings]]
tid = 2283
name = "コイ☆セント"
tmdb_series_id = 118026
tmdb_season_id = 0

[[mappings]]
tid = 2284
name = "ノラゲキ！"
tmdb_series_id = 111608
tmdb_season_id = 0

[[mappings]]
tid = 2529
name = "CYBERSIX"
tmdb_series_id = 22784
tmdb_season_id = 1

[[mappings]]
tid = 2531
name = "姫ちゃんのリボン"
tmdb_series_id = 43230
tmdb_season_id = 1

[[mappings]]
tid = 2729
name = "獣旋バトル モンスーノ"
tmdb_series_id = 56402
tmdb_season_id = 0

[[mappings]]
tid = 2849
name = "ヒピラくん"
tmdb_series_id = 85910
tmdb_season_id = 0

[[mappings]]
tid = 2998
name = "映画テルマエ・ロマエ"
tmdb_series_id = 105210
tmdb_season_id = 0

[[mappings]]
tid = 3009
name = "映画 君に届け"
tmdb_series_id = 59944
tmdb_season_id = 0

[[mappings]]
tid = 3082
name = "仮面ライダー×スーパー戦隊 スーパーヒーロー大戦"
tmdb_series_id = 241697
tmdb_season_id = 0

[[mappings]]
tid = 3194
name = "サラとダックン"
tmdb_series_id = 46866
tmdb_season_id = 0

[[mappings]]
tid = 3215
name = "D・N・A2 ～何処かで失くしたあいつのアイツ～"
tmdb_series_id = 43384
tmdb_season_id = 1

[[mappings]]
tid = 3241
name = "スペース☆ダンディ"
tmdb_series_id = 60874
tmdb_season_id = 1

[[mappings]]
tid = 3274
name = "HK/変態仮面"
tmdb_series_id = 204342
tmdb_season_id = 0

[[mappings]]
tid = 3277
name = "荒川アンダー ザ ブリッジ THE MOVIE"
tmdb_series_id = 142386
tmdb_season_id = 0

[[mappings]]
tid = 3380
name = "ハイキュー!!"
tmdb_series_id = 60863
tmdb_season_id = 0

[[mappings]]
tid = 3413
name = "THE NEXT GENERATION パトレイバー"
tmdb_series_id = 1078987
tmdb_season_id = 0

[[mappings]]
tid = 3538
name = "アリスSOS"
tmdb_series_id = 20664
tmdb_season_id = 0

[[mappings]]
tid = 3620
name = "ローリング☆ガールズ"
tmdb_series_id = 70634
tmdb_season_id = 1

[[mappings]]
tid = 3692
name = "アドベンチャー・タイム"
tmdb_series_id = 15260
tmdb_season_id = 0

[[mappings]]
tid = 3709
name = "アルティメット・スパイダーマン ウェブ・ウォーリアーズ"
tmdb_series_id = 34391
tmdb_season_id = 0

[[mappings]]
tid = 3740
name = "レゴ ニンジャゴー"
tmdb_series_id = 38693
tmdb_season_id = 0

[[mappings]]
tid = 3800
name = "Classroom☆Crisis"
tmdb_series_id = 63499
tmdb_season_id = 0

[[mappings]]
tid = 3928
name = "PEANUTS スヌーピー-ショートアニメ-"
tmdb_series_id = 66514
tmdb_season_id = 0

[[mappings]]
tid = 3951
name = "ちいさなプリンセス ソフィア"
tmdb_series_id = 46928
tmdb_season_id = 0

[[mappings]]
tid = 3969
name = "スター・ウォーズ 反乱者たち"
tmdb_series_id = 60554
tmdb_season_id = 0

[[mappings]]
tid = 4056
name = "烈車戦隊トッキュウジャーVSキョウリュウジャー THE MOVIE"
tmdb_series_id = 313462
tmdb_season_id = 0

[[mappings]]
tid = 4112
name = "アルティメット・スパイダーマン VS シニスター・シックス"
tmdb_series_id = 34391
tmdb_season_id = 4

[[mappings]]
tid = 4119
name = "文豪ストレイドッグス"
tmdb_series_id = 65931
tmdb_season_id = 0

[[mappings]]
tid = 4123
name = "レゴ ニンジャゴー(天空の海賊編)"
tmdb_series_id = 38693
tmdb_season_id = 0

[[mappings]]
tid = 4152
name = "ぼのぼの(2016)"
tmdb_series_id = 66751
tmdb_season_id = 1

[[mappings]]
tid = 4179
name = "あはれ！名作くん"
tmdb_series_id = 128386
tmdb_season_id = 0

[[mappings]]
tid = 4187
name = "カミワザ・ワンダ"
tmdb_series_id = 128862
tmdb_season_id = 1

[[mappings]]
tid = 4221
name = "RS計画 -Rebirth Storage-"
tmdb_series_id = 423124
tmdb_season_id = 0

[[mappings]]
tid = 4252
name = "一人之下 the outcast"
tmdb_series_id = 67063
tmdb_season_id = 1

[[mappings]]
tid = 4358
name = "Bloodivores"
tmdb_series_id = 68078
tmdb_season_id = 1

[[mappings]]
tid = 4359
name = "アベンジャーズ・アッセンブル"
tmdb_series_id = 59427
tmdb_season_id = 0

[[mappings]]
tid = 4380
name = "レゴ ニンジャゴー(よみがえりの日編)"
tmdb_series_id = 38693
tmdb_season_id = 0

[[mappings]]
tid = 4525
name = "レゴ ニンジャゴー(時空の支配者編)"
tmdb_series_id = 38693
tmdb_season_id = 0

[[mappings]]
tid = 4527
name = "アバローのプリンセス エレナ"
tmdb_series_id = 67175
tmdb_season_id = 0

[[mappings]]
tid = 4563
name = "兄に付ける薬はない！-快把我哥帯走-"
tmdb_series_id = 70972
tmdb_season_id = 1

[[mappings]]
tid = 4573
name = "100%パスカル先生＆プリプリちぃちゃん!!"
tmdb_series_id = 71068
tmdb_season_id = 1

[[mappings]]
tid = 4594
name = "ぼのぼの(1995)"
tmdb_series_id = 66569
tmdb_season_id = 0

[[mappings]]
tid = 4624
name = "無責任ギャラクシー☆タイラー"
tmdb_series_id = 72817
tmdb_season_id = 1

[[mappings]]
tid = 4729
name = "GLAMOROUS HEROES"
tmdb_series_id = 90579
tmdb_season_id = 1

[[mappings]]
tid = 4736
name = "ディアホライゾン(被)"
tmdb_series_id = 74085
tmdb_season_id = 1

[[mappings]]
tid = 4818
name = "剣王朝"
tmdb_series_id = 79594
tmdb_season_id = 0

[[mappings]]
tid = 4821
name = "一人之下 the outcast (羅天大醮篇／全性篇)"
tmdb_series_id = 67063
tmdb_season_id = 0

[[mappings]]
tid = 4838
name = "SPIRITPACT -黄泉の契り-"
tmdb_series_id = 69344
tmdb_season_id = 2

[[mappings]]
tid = 4923
name = "実験品家族 -クリーチャーズ・ファミリー・デイズ-"
tmdb_series_id = 78521
tmdb_season_id = 1

[[mappings]]
tid = 4925
name = "レディスポ"
tmdb_series_id = 78480
tmdb_season_id = 1

[[mappings]]
tid = 4936
name = "SNSポリス"
tmdb_series_id = 78500
tmdb_season_id = 1

[[mappings]]
tid = 4994
name = "働くお兄さん！の2！"
tmdb_series_id = 76174
tmdb_season_id = 2

[[mappings]]
tid = 5002
name = "焼肉店センゴク"
tmdb_series_id = 288121
tmdb_season_id = 1

[[mappings]]
tid = 5004
name = "ミッキーマウスとロードレーサーズ"
tmdb_series_id = 70823
tmdb_season_id = 1

[[mappings]]
tid = 5021
name = "ミラキュラス レディバグ＆シャノワール"
tmdb_series_id = 65334
tmdb_season_id = 0

[[mappings]]
tid = 5097
name = "トロールズ：シング・ダンス・ハグ！"
tmdb_series_id = 76205
tmdb_season_id = 0

[[mappings]]
tid = 5098
name = "ほら、耳がみえてるよ！"
tmdb_series_id = 89576
tmdb_season_id = 1

[[mappings]]
tid = 5144
name = "3D彼女 リアルガール(第2シーズン)"
tmdb_series_id = 77721
tmdb_season_id = 2

[[mappings]]
tid = 5176
name = "HK 変態仮面 アブノーマル・クライシス"
tmdb_series_id = 403310
tmdb_season_id = 0

[[mappings]]
tid = 5254
name = "アイドルマスター シンデレラガールズ劇場 CLIMAX SEASON"
tmdb_series_id = 71012
tmdb_season_id = 4

[[mappings]]
tid = 5271
name = "文豪ストレイドッグス(第3シーズン)"
tmdb_series_id = 65931
tmdb_season_id = 0

[[mappings]]
tid = 5279
name = "パウ・パトロール"
tmdb_series_id = 57532
tmdb_season_id = 0

[[mappings]]
tid = 5389
name = "ヒックとドラゴン：新たな世界へ！"
tmdb_series_id = 78173
tmdb_season_id = 0

[[mappings]]
tid = 5393
name = "ビジネスフィッシュ"
tmdb_series_id = 91890
tmdb_season_id = 1

[[mappings]]
tid = 5473
name = "耐え子の日常"
tmdb_series_id = 94299
tmdb_season_id = 0

[[mappings]]
tid = 5499
name = "バジャのスタジオ"
tmdb_series_id = 475997
tmdb_season_id = 0

[[mappings]]
tid = 5577
name = "パウ・パトロール(シーズン2)"
tmdb_series_id = 57532
tmdb_season_id = 2

[[mappings]]
tid = 5715
name = "耐え子の日常(第二期)"
tmdb_series_id = 94299
tmdb_season_id = 0

[[mappings]]
tid = 5733
name = "バジャのスタジオ～バジャのみた海～"
tmdb_series_id = 675392
tmdb_season_id = 0

[[mappings]]
tid = 5753
name = "魔道祖師 前塵編"
tmdb_series_id = 80732
tmdb_season_id = 1

[[mappings]]
tid = 5788
name = "ツキウタ。 THE ANIMATION2"
tmdb_series_id = 67153
tmdb_season_id = 2

[[mappings]]
tid = 5826
name = "魔道祖師 羨雲編"
tmdb_series_id = 80732
tmdb_season_id = 2

[[mappings]]
tid = 5862
name = "アーヤと魔女"
tmdb_series_id = 683127
tmdb_season_id = 0

[[mappings]]
tid = 5885
name = "スケートリーディング☆スターズ"
tmdb_series_id = 96042
tmdb_season_id = 1

[[mappings]]
tid = 5891
name = "ヒックとドラゴン：新たな世界へ！(シーズン2)"
tmdb_series_id = 78173
tmdb_season_id = 2

[[mappings]]
tid = 5894
name = "パウ・パトロール(シーズン3)"
tmdb_series_id = 57532
tmdb_season_id = 3

[[mappings]]
tid = 5898
name = "劇場版 新幹線変形ロボ シンカリオン 未来からきた神速のALFA-X"
tmdb_series_id = 635687
tmdb_season_id = 0

[[mappings]]
tid = 5956
name = "ダイナ荘びより"
tmdb_series_id = 122474
tmdb_season_id = 1

[[mappings]]
tid = 5969
name = "レゴ モンキーキッド"
tmdb_series_id = 106251
tmdb_season_id = 0

[[mappings]]
tid = 6010
name = "映画 ねこねこ日本史 ～龍馬のはちゃめちゃタイムトラベルぜよ！～"
tmdb_series_id = 1013490
tmdb_season_id = 0

[[mappings]]
tid = 6069
name = "TSUKIPRO THE ANIMATION2"
tmdb_series_id = 74187
tmdb_season_id = 2

[[mappings]]
tid = 6075
name = "天官賜福"
tmdb_series_id = 112398
tmdb_season_id = 1

[[mappings]]
tid = 6160
name = "海賊王女"
tmdb_series_id = 106480
tmdb_season_id = 1

[[mappings]]
tid = 6171
name = "闘神機ジーズフレーム"
tmdb_series_id = 135691
tmdb_season_id = 1

[[mappings]]
tid = 6236
name = "パウ・パトロール(シーズン4)"
tmdb_series_id = 57532
tmdb_season_id = 4

[[mappings]]
tid = 6242
name = "時光代理人 -LINK CLICK-"
tmdb_series_id = 123542
tmdb_season_id = 1

[[mappings]]
tid = 6403
name = "5億年ボタン【公式】～菅原そうたのショートショート～"
tmdb_series_id = 205055
tmdb_season_id = 0

[[mappings]]
tid = 6406
name = "神クズ☆アイドル"
tmdb_series_id = 139551
tmdb_season_id = 1

[[mappings]]
tid = 6427
name = "深海のサバイバル！"
tmdb_series_id = 843245
tmdb_season_id = 0

[[mappings]]
tid = 6484
name = "万聖街"
tmdb_series_id = 106402
tmdb_season_id = 0

[[mappings]]
tid = 6525
name = "魔道祖師 完結編"
tmdb_series_id = 80732
tmdb_season_id = 3

[[mappings]]
tid = 6557
name = "齢5000年の草食ドラゴン、いわれなき邪竜認定"
tmdb_series_id = 139161
tmdb_season_id = 0

[[mappings]]
tid = 6575
name = "文豪ストレイドッグス(第4シーズン)"
tmdb_series_id = 65931
tmdb_season_id = 4

[[mappings]]
tid = 6668
name = "アニメーション紀行 マルコ･ポーロの冒険"
tmdb_series_id = 28665
tmdb_season_id = 1

[[mappings]]
tid = 6687
name = "それしか ないわけ ないでしょう"
tmdb_series_id = 223562
tmdb_season_id = 1

[[mappings]]
tid = 6699
name = "キャッチ！ティニピン"
tmdb_series_id = 204091
tmdb_season_id = 1

[[mappings]]
tid = 6745
name = "文豪ストレイドッグス(第5シーズン)"
tmdb_series_id = 65931
tmdb_season_id = 5

[[mappings]]
tid = 6750
name = "フェ～レンザイ -神さまの日常-"
tmdb_series_id = 94039
tmdb_season_id = 0

[[mappings]]
tid = 6780
name = "ハートカクテル カラフル(夏編)"
tmdb_series_id = 290837
tmdb_season_id = 2

[[mappings]]
tid = 6818
name = "攻略うぉんてっど！～異世界救います!?～"
tmdb_series_id = 139171
tmdb_season_id = 0

[[mappings]]
tid = 6892
name = "ハートカクテル カラフル(冬編)"
tmdb_series_id = 290837
tmdb_season_id = 3

[[mappings]]
tid = 6985
name = "映画ざんねんないきもの事典"
tmdb_series_id = 994313
tmdb_season_id = 0

[[mappings]]
tid = 7012
name = "アイドルマスター シャイニーカラーズ"
tmdb_series_id = 248086
tmdb_season_id = 1

[[mappings]]
tid = 7036
name = "時光代理人 -LINK CLICK-Ⅱ"
tmdb_series_id = 123542
tmdb_season_id = 2

[[mappings]]
tid = 7055
name = "ギャビーのドールハウス"
tmdb_series_id = 111474
tmdb_season_id = 1

[[mappings]]
tid = 7060
name = "ARNOLD & PUPPETS"
tmdb_series_id = 259869
tmdb_season_id = 1

[[mappings]]
tid = 7067
name = "SHIBUYA♡HACHI"
tmdb_series_id = 246676
tmdb_season_id = 1

[[mappings]]
tid = 7105
name = "異世界スーサイド・スクワッド"
tmdb_series_id = 229926
tmdb_season_id = 1

[[mappings]]
tid = 7136
name = "下の階には澪がいる"
tmdb_series_id = 0
tmdb_season_id = 0

[[mappings]]
tid = 7193
name = "アイドルマスター シャイニーカラーズ 2nd season"
tmdb_series_id = 248086
tmdb_season_id = 2

[[mappings]]
tid = 7229
name = "百妖譜 第二期"
tmdb_series_id = 101099
tmdb_season_id = 2

[[mappings]]
tid = 7252
name = "齢5000年の草食ドラゴン、いわれなき邪竜認定 season2"
tmdb_series_id = 139161
tmdb_season_id = 2

[[mappings]]
tid = 7257
name = "キラキラ キャッチ！ティニピン"
tmdb_series_id = 0
tmdb_season_id = 0

[[mappings]]
tid = 7264
name = "アサティール2 未来の昔ばなし"
tmdb_series_id = 0
tmdb_season_id = 0

[[mappings]]
tid = 7287
name = "SAKAMOTO DAYS"
tmdb_series_id = 207332
tmdb_season_id = 1

[[mappings]]
tid = 7292
name = "RINGING FATE"
tmdb_series_id = 241594
tmdb_season_id = 1

[[mappings]]
tid = 7337
name = "猫になりたい田万川くん"
tmdb_series_id = 1410345
tmdb_season_id = 0

[[mappings]]
tid = 7411
name = "クラシック★スターズ"
tmdb_series_id = 283360
tmdb_season_id = 1

[[mappings]]
tid = 7415
name = "LAZARUS ラザロ"
tmdb_series_id = 231003
tmdb_season_id = 1

[[mappings]]
tid = 7425
name = "この恋で鼻血を止めて"
tmdb_series_id = 258265
tmdb_season_id = 1

[[mappings]]
tid = 7435
name = "TO BE HERO X"
tmdb_series_id = 0
tmdb_season_id = 0

[[mappings]]
tid = 7488
name = "SAKAMOTO DAYS SEASON 1 Part 2"
tmdb_series_id = 207332
tmdb_season_id = 1

[[mappings]]
tid = 7509
name = "転生宗主の覇道譚～すべてを吞み込むサカナと這い上がる～"
tmdb_series_id = 280078
tmdb_season_id = 1

[[mappings]]
tid = 7535
name = "シークレット キャッチ！ティニピン"
tmdb_series_id = 0
tmdb_season_id = 0

[[mappings]]
tid = 7536
name = "銀河特急 ミルキー☆サブウェイ"
tmdb_series_id = 294766
tmdb_season_id = 1
