# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: "Setup Rust"
description: "Setup rust"
inputs:
  sccache:
    description: "sccache version"
    required: true
    default: ""
  sccache_disable_annotations:
    description: "sccache disable_annotations"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      with:
        disable_annotations: ${{ inputs.sccache_disable_annotations == 'true' }}
        version: ${{ inputs.sccache }}

    - name: Cache rustup
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~/.rustup/settings.toml
          ~/.rustup/toolchains/1.*
        key: v0-rust-rustup-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/rust-toolchain.toml') }}

    - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
      with:
        cache-shared-key: cargo-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
